env: MiniGrid-Empty-16x16-v0
train: true
evaluate: false
episode_max_frame: 1000
seed: 0
episodes: 10
pause: 0.1 # pause duration between two consequent actions of the agent (default: 0.1)
procs: 16 # number of processes (default: 16)
gif: '' # store output as gif with the given filename
